name: Benchmarks
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"

jobs:
  bench_elgamal:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-27
          override: true
          components: rustfmt, clippy
      - name: Bench elgamal
        run: cargo bench --verbose --bench elgamal

  bench_poseidon:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-27
          override: true
          components: rustfmt, clippy
      - name: Bench poseidon
        run: cargo bench --verbose --bench poseidon

  bench_einsum_accum_matmul:
    runs-on: self-hosted
    needs: [bench_poseidon]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-27
          override: true
          components: rustfmt, clippy
      - name: Bench embd attn1 einsum
        run: cargo bench --verbose --bench embd_attn1_einsum
      - name: Bench embd attn2 einsum
        run: cargo bench --verbose --bench embd_attn2_einsum
      - name: Bench head attn1 einsum
        run: cargo bench --verbose --bench head_attn1_einsum
      - name: Bench head attn2 einsum
        run: cargo bench --verbose --bench head_attn2_einsum
