name: Benchmarks
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"
jobs:
  benchmarks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-03
          override: true
          components: rustfmt, clippy
      - name: Bench embd attn1 einsum
        run: cargo bench --verbose --bench embd_attn1_einsum